<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Scoring Married - CS Used</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1d47faab-6102-4488-a287-16020538987f</testSuiteGuid>
   <testCaseLink>
      <guid>60184557-b2e4-4062-a953-2aa5a8981a24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Engine_Scoring/Engine Scoring</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ba26ac96-02ba-4eb5-b226-2db303fe45d0</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-36</value>
         </iterationEntity>
         <testDataId>Data Files/married 23-11-22/CS Used - Married</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2188286-adc5-4453-8960-5516180f515f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>source</value>
         <variableId>7975415a-e071-43db-a6f8-6e6edc023f18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0ba0882-091f-4375-8c1a-2a2d875017cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83920f0b-5326-4345-a04b-6ae2c587420d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>branch</value>
         <variableId>4a1fc242-89a0-4c68-8634-6939f99c7e26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec5a6eae-3643-4acb-b57a-7c621c88e455</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>marital</value>
         <variableId>7ae2ee76-dab5-4435-8c60-3f3d8dd97910</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45b68a3b-ef1a-4fe6-9835-2cbc51e65189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24e40a17-090c-4206-9f8b-5755effdef5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c922910c-dec7-40f9-b992-e876aec095c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>custname</value>
         <variableId>fa4d2ff2-44e0-4e3a-a86a-87fa3775c781</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ebd4ef8-41dd-4378-85e9-2e90bdddf496</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id_no</value>
         <variableId>f53ca30e-c8f9-47f9-9792-9f68e4f8737c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cc2a571-52d5-454f-8cd8-68e3512cd637</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>birthdate</value>
         <variableId>37397f4a-4e65-4232-99b3-c25c57bf528e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d4e5448-5ab6-442c-94eb-3c327a19ec10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04f03a28-95b0-4fbb-ac53-bc86c5612ef4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c961634c-f1c1-4ed1-b282-b19f80f37ba1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>188b08f5-6f4e-49ca-bfa0-2fca417de26d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6301960f-2a58-4915-bd4a-219b48bcba71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98200749-b85b-4bb5-9952-74382b727f80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc4580cb-2b8a-4711-b51e-0125be850766</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e91d60d5-5e2e-4ff2-9ff4-f0fb0d187231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17f904a1-6c65-47b7-9806-d8d3c4310def</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e63561d-7bc0-49ca-b8c3-3f912ab87bf6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2061c8f9-efc7-4699-908d-6dfb0d9a644f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f61628e-f937-4ffc-ba80-8b07e51501de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b20f47d-68fa-492f-a2bf-940700cd8ba3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9424831-804a-4a5b-adcd-31a7c2c2e431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4529269-f9b3-4e53-82a6-46703673b94a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a8fa2d9-a98a-4ebc-870d-65c31e8b6db6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a825cc7-8ede-4725-a7ed-28ad224e11d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1b9ec05-857c-4789-b7f5-20171605ff79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a428888b-c62c-437b-9fa7-f2f00a1e5e0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb00ab2-6a84-4895-9d5a-99bee9c6b374</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7851b640-6188-4f9a-ad39-ab462b378867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b1a3bf9-8bfe-49ad-ba3b-cbce1230cca1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>spouse_name</value>
         <variableId>6263781f-555e-4c3a-880f-a3329e0663e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468d4dda-6cb9-43ac-b703-535e9cfd7dc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20c8a7da-0371-456c-acd2-ee1f2d2b55f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>spouse_idno</value>
         <variableId>e0ec505a-9308-4845-bff3-89795ba3044d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d44295b7-8782-4462-bc8a-54b0e49cf39c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>spouse_birthdate</value>
         <variableId>ee5d33f1-6705-4433-882e-30f4eb45ed5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbcefc0e-04c9-4089-bbfd-4708b271d37d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8e77ec0-50a2-409a-abbc-8b4e83bb943f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6024f7ba-12d7-4166-abf7-40267dd22190</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42ee1076-6f14-41d0-9e27-2f56f2074eae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a331491e-15d4-4304-ad17-0e9ffb50c2c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d89c6144-2035-4a6c-832a-0bf6e19ad530</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>707ff89d-d7c3-4cbc-b7bb-5e029fd4910b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6cae4b8-6a2d-4e7c-9df5-d709af218c5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ec9f601-9548-4240-940c-76b7bd9929ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab70bebf-ecd8-4be5-ad26-ffd7dc86b072</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e07a3fc-c365-4b2d-a3a0-e189c27f5aef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f0979a1-aa31-4b4f-86f5-d80ef39e0468</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfd0bc8e-9db3-4141-8d3d-085b3a96d3e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acf4adac-a38c-4a2e-a825-3dfede81e89e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b349c10f-6a83-439e-b87b-179e337dfcf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d6e51d-3e61-4cec-afa0-30d1c479134f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e275881d-58b2-4b04-939a-941d267cdab1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3055bb7-ca10-48b4-bb71-d4e880e9d910</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>811e5469-db32-4844-bb61-8032bb17718d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd184564-aa59-4e8b-bc13-52a76a6b5cc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9337de1-6969-44bc-877e-1809bf72ce02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b16edaf3-bf8e-4217-868e-ab7e58e76b8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ba7fbfd-a31a-4074-bdf0-0019d29b38fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01d6342f-ffcc-4d69-bb6a-abc3576e5b04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8249ccb1-d748-4109-a312-390170d11d6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>604aea1a-6069-4d50-9924-5296018db68f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7985330-e0c6-413c-8d2b-f9b13ecd6170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7191991c-fbf3-4ba8-93df-9269d1431ab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08056b2f-4cd7-4bf7-89d6-97dc2f4b2a48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6719f63-dd83-4ffe-a2a0-1c19f8fa3d57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c5deb52-10b0-4843-8a4a-c8bb840c95d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be039fb3-761f-4b43-95c0-d4b7048a9618</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccd24d43-894e-4c71-adf2-788efc5b226a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5b30c62-b890-4150-8b4e-bed8ad44238e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3a20be-8220-494a-9495-a3df8db654c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d34bf23f-5523-4cb9-a8f8-83a85cfb92f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a58f8bc1-c424-415b-8138-8caca9499996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69d02fcd-9ed8-47d1-8d61-5b962aa39ce0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ad31b7f-86bf-4ddb-a116-b578e1f81333</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74f6230a-1bd3-446d-913e-f7b94c50453b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50a9f658-9942-43a8-9e04-ddcb198802d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c124953-bc78-45f1-81fe-959fafda96f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0677e9cc-ee06-451f-869a-75cc5c224e30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17e31916-e95c-4927-adf2-d0b5c6b3dddf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c1c5217-d2ce-4cbe-82b0-01dd8e922f3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2091be7-3fd1-42e5-b5dc-203e5665813a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d9c97d9-471e-426b-b3aa-4a05f484c787</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f4240f-31be-4b34-8c11-6769883855f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>515cc93e-6d26-4da1-9f30-f2588f242777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9672966a-e430-4968-be48-eb1b612a8e1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65844ee3-b629-4e27-949f-48c00fd3b6f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50fe18ea-e3aa-44c7-a3c0-1c27a1ccd1b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ffbbaca-4f0a-4fba-8f5d-4eb1c0f7424d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca4bdeec-ce62-40e0-a6bd-fbf63fefbf39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91f18405-4e8e-4de5-9b6d-106f345e0388</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3a74609-7110-46c9-bf61-05adf586aec7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>970901af-d296-444e-b30c-7033590f4215</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c50bb1c-c4b6-47ec-af0a-b55720a9da7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f90118c2-8c22-4327-83d3-46bb42954ecd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc1506f5-5b09-4883-abb9-a0248edfe570</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caf38065-9471-497a-8b0f-b9d2b1f8c171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a59b957d-26bd-483f-8904-c82910702ff3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7046a219-d5a7-4616-8d74-dc063f168bf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4986efd8-1c60-43a5-acd7-195f1ee99d5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e5c128-3bc9-4e50-b41f-2939428aa0d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18d14e05-5f57-4a74-8788-78c3157f3a9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96879ee8-f7e0-462a-888b-712ed04ac818</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3a8cb4f-35e6-4b4e-b09a-914b17ef0dfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5abc3431-c7fc-4241-8621-f38494f7825d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4e57438-218b-4903-80e5-181e093212dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e2c0069-4d1b-4e1a-b5e2-545adac8efe6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d89057f-c073-4c70-8ad9-7e57d32fef9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcb53ab9-e4e1-410f-89a0-1713eab2a170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab546bad-f5fe-4430-8f08-378bf2417cdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc4d769b-1b59-4f0e-b8d8-0c5db0d4cd3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45c93b2d-e920-43fa-be10-a0a77262714b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2caecf11-0bae-4c9b-9a9c-64f2de8e19bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4406f7f-67b4-46f6-9359-601095d7735e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfc7fc75-bbdb-4362-8294-3859796382f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>124c3e4f-fffe-41fd-9b44-3a74d08e0602</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e91e7d2-a3f1-4b89-9254-96c1ccda519e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90a1e556-fccf-4247-afed-41b855582182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c776c05-87df-4dc4-872d-cab88dbb153c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1635165f-773f-4b47-9fd4-dfb022351f0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1abb5975-5690-47cb-b605-b6955cee8d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbb138be-1ee3-4213-8030-77d34f220533</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f100659b-422d-4047-a57a-c0f483df4aef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1248484e-76d5-4ebe-8ad1-b1f71e185748</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a5f6626-2636-4cd1-bb6e-83091e685751</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1eae55e-10d6-48f9-b1b0-d8c0a493344b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9b5922a-78c4-41a6-ae0c-86c1532111d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba4ad9b1-99f3-45a6-8304-d7cf0da6780a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c2be59a-ddda-4779-880c-30f104e2f117</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>816de3b7-d59a-403f-9a4b-6ccc0ae69ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d3741be-7a58-47e4-9e24-753b1d636a48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>133e6f76-6ae2-45e0-b714-20c95324c99f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b2f8af7-55be-4f55-a60e-516b39e187fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5e8f38c-ebe9-4d5c-a0db-bd0af6554432</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>118f4ca2-a846-441e-b452-a3ae862fc05a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89405f6f-c2af-4174-8049-2f9aa805d046</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b5fe6dc-8a81-453b-b785-aed67e3c843f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf674fde-29f4-4c12-acc2-535b0ac59e3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37aa193a-71dc-47ab-895c-09156849f365</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>767ca683-71ee-4dac-84ec-d9646cc37866</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bb357e6-1349-4cc7-8ae9-e9b12003778b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d51cc34c-f095-43fd-9e87-1ab1d0cf5800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dbabea2-3ff7-4310-8fbe-d8f296192855</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb528b4d-446e-499b-9840-93e32bcf055b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3fea692-9434-45f2-a613-741f5827efd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f8c3f5b-d135-4753-bc2b-fe1a37281feb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>657806dc-4ecd-4ada-a75c-a690cb8e8ff6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7becca4-2b35-454c-8a42-e9779b49af77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70796540-bd68-4864-8536-4cfccad25ab1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60e0463d-5379-45f3-9f66-c034597790f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7341d25b-e61b-4140-a2d0-5998caf08ee0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>364c2cfd-8e72-4619-a8dc-29378c4117da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73169515-5234-43a1-8c2d-e633b86a43b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>final_result</value>
         <variableId>2a82000d-5a6e-4a26-8878-d74fcffcf0db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba26ac96-02ba-4eb5-b226-2db303fe45d0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>No</value>
         <variableId>461d213f-2f4b-4b71-ac78-29b6e3c148c4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
