<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Search_ME</name>
   <tag></tag>
   <elementGuidId>fa3071e3-ec42-481a-b83f-b82d90bb4040</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;MobileID\&quot;: \&quot;${MID}\&quot;,\n  \&quot;SourceApps\&quot;: \&quot;${source}\&quot;,\n  \&quot;UserInfo\&quot;: {\n    \&quot;ipAddress\&quot;: \&quot;${ip}\&quot;,\n    \&quot;userid\&quot;: \&quot;${userid}\&quot;\n  },\n  \&quot;initiation\&quot;: {\n    \&quot;Cabang\&quot;: \&quot;${branch}\&quot;,\n    \&quot;TypeConsumen\&quot;: \&quot;${tipekons}\&quot;,\n    \&quot;StatusPerkawinan\&quot;: \&quot;${marital}\&quot;,\n    \&quot;Penjamin\&quot;: \&quot;${penjamin}\&quot;,\n    \&quot;TypePenjamin\&quot;: \&quot;\&quot;,\n    \&quot;Cluster\&quot;: \&quot;\&quot;\n  },\n  \&quot;PersonalData\&quot;: {\n    \&quot;Nama\&quot;: \&quot;${custname}\&quot;,\n    \&quot;IdentityType\&quot;: \&quot;${id_type}\&quot;,\n    \&quot;IdentityNo\&quot;: \&quot;${id_no}\&quot;,\n    \&quot;BirthPlace\&quot;: \&quot;${birthplace}\&quot;,\n    \&quot;BirthDate\&quot;: \&quot;${birthdate}\&quot;,\n    \&quot;alamatKTP\&quot;: \&quot;${alamatktp}\&quot;,\n    \&quot;Kelurahan\&quot;: \&quot;${kelurahan}\&quot;,\n    \&quot;kecamatan\&quot;: \&quot;${kecamatan}\&quot;,\n    \&quot;Kabupaten\&quot;: \&quot;${kabupaten}\&quot;,\n    \&quot;Provinsi\&quot;: \&quot;${provinsi}\&quot;,\n    \&quot;KodePos\&quot;: \&quot;${kodepos}\&quot;,\n    \&quot;Jenkel\&quot;: \&quot;${jenkel}\&quot;,\n    \&quot;SupportPerson\&quot;: \&quot;\&quot;,\n    \&quot;NamaIbuKandung\&quot;: \&quot;${namaibu}\&quot;,\n    \&quot;Agama\&quot;: \&quot;${agama}\&quot;\n  },\n  \&quot;Occuption\&quot;: {\n    \&quot;Pekerjaan\&quot;: \&quot;${job}\&quot;,\n    \&quot;EconomyCode\&quot;: \&quot;${ecocode}\&quot;,\n    \&quot;EstablishedSince\&quot;: \&quot;${est_since}\&quot;,\n    \&quot;JenisUsaha\&quot;: \&quot;${jenisusaha}\&quot;,\n    \&quot;jabatan\&quot;: \&quot;${jabatan}\&quot;,\n    \&quot;totalPenghasilan\&quot;: \&quot;${income}\&quot;,\n    \&quot;Alamat\&quot;: \&quot;\&quot;,\n    \&quot;KodeFax\&quot;: \&quot;\&quot;,\n    \&quot;Kecamatan\&quot;: \&quot;\&quot;,\n    \&quot;KodePos\&quot;: \&quot;\&quot;,\n    \&quot;KodeNoTelp\&quot;: \&quot;\&quot;,\n    \&quot;NoTelp\&quot;: \&quot;\&quot;,\n    \&quot;ExtTelp\&quot;: \&quot;\&quot;\n  },\n  \&quot;SposeData\&quot;: {\n    \&quot;NamaSpouse\&quot;: \&quot;${spouse_name}\&quot;,\n    \&quot;IdentityTypeSpouse\&quot;: \&quot;${spouse_idtype}\&quot;,\n    \&quot;JenKel\&quot;: \&quot;\&quot;,\n    \&quot;NomorKTP\&quot;: \&quot;${spouse_idno}\&quot;,\n    \&quot;Agama\&quot;: \&quot;\&quot;,\n    \&quot;BirthDate\&quot;: \&quot;${spouse_birthdate}\&quot;,\n    \&quot;BirthPlace\&quot;: \&quot;\&quot;,\n    \&quot;Alamat\&quot;: \&quot;\&quot;,\n    \&quot;Kelurahan\&quot;: \&quot;\&quot;,\n    \&quot;Kecamatan\&quot;: \&quot;\&quot;,\n    \&quot;Kabupaten\&quot;: \&quot;\&quot;,\n    \&quot;Provinsi\&quot;: \&quot;\&quot;,\n    \&quot;Occupation_KTP\&quot;: \&quot;\&quot;,\n    \&quot;PekerjaanSpouse\&quot;: \&quot;\&quot;,\n    \&quot;NamaPerusahaan\&quot;: \&quot;\&quot;,\n    \&quot;Jabatan\&quot;: \&quot;\&quot;,\n    \&quot;Occupation_KartuNama\&quot;: \&quot;\&quot;,\n    \&quot;alamatPerusahaan\&quot;: \&quot;\&quot;,\n    \&quot;FaxPerusahaan\&quot;: \&quot;\&quot;,\n    \&quot;KecamatanPerusahaan\&quot;: \&quot;\&quot;,\n    \&quot;KodePosPerusahaan\&quot;: \&quot;\&quot;,\n    \&quot;KodeNomorTelpPerusahaan\&quot;: \&quot;\&quot;,\n    \&quot;NotelpPerusahaan\&quot;: \&quot;\&quot;,\n    \&quot;ExtTelpPerusahaan\&quot;: \&quot;\&quot;\n  },\n  \&quot;Dealer\&quot;: {\n    \&quot;DealerName\&quot;: \&quot;${dealername}\&quot;,\n    \&quot;Cabang\&quot;: \&quot;${dealerbranch}\&quot;,\n    \&quot;Alamat\&quot;: \&quot;${dealer_addr}\&quot;,\n    \&quot;Kota\&quot;: \&quot;${dealer_kota}\&quot;,\n    \&quot;NoHP\&quot;: \&quot;${dealer_hp}\&quot;,\n    \&quot;Fax\&quot;: \&quot;${dealer_fax}\&quot;,\n    \&quot;Authorize\&quot;: \&quot;${dealer_auth}\&quot;,\n    \&quot;NoRek\&quot;: \&quot;${dealer_norek}\&quot;\n  },\n  \&quot;Vehicle\&quot;: {\n    \&quot;CarCondition\&quot;: \&quot;${car_cond}\&quot;,\n    \&quot;Brand\&quot;: \&quot;${brand}\&quot;,\n    \&quot;Model\&quot;: \&quot;${model}\&quot;,\n    \&quot;Type\&quot;: \&quot;${type}\&quot;,\n    \&quot;Year\&quot;: \&quot;${year}\&quot;,\n    \&quot;Kind\&quot;: \&quot;${kind}\&quot;,\n    \&quot;Purpose\&quot;: \&quot;${purpose}\&quot;,\n    \&quot;Color\&quot;: \&quot;${color}\&quot;,\n    \&quot;EngineNo\&quot;: \&quot;${engineno}\&quot;,\n    \&quot;BodyNo\&quot;: \&quot;${bodyno}\&quot;,\n    \&quot;BPKBOwner\&quot;: \&quot;${bpkb_owner}\&quot;,\n    \&quot;PoliceNo\&quot;: \&quot;\&quot;,\n    \&quot;BPKBNumber\&quot;: \&quot;\&quot;\n  },\n  \&quot;LoanData\&quot;: {\n    \&quot;OTR\&quot;: \&quot;${otr}\&quot;,\n    \&quot;DP\&quot;: \&quot;${dp}\&quot;,\n    \&quot;DP_Percent\&quot;: \&quot;${dp_percent}\&quot;,\n    \&quot;Principal\&quot;: \&quot;${principal}\&quot;,\n    \&quot;ResidualValue\&quot;: \&quot;\&quot;,\n    \&quot;Tenor\&quot;: \&quot;${tenor}\&quot;,\n    \&quot;FlatRate\&quot;: \&quot;${flatrate}\&quot;,\n    \&quot;EffectiveRate\&quot;: \&quot;${effrate}\&quot;,\n    \&quot;Installment\&quot;: \&quot;${installment}\&quot;,\n    \&quot;LoanType\&quot;: \&quot;${loan_type}\&quot;,\n    \&quot;TotalOutstanding\&quot;: \&quot;\&quot;,\n    \&quot;BiayaProcessPembiayaan\&quot;: \&quot;${biaya_pp}\&quot;,\n    \&quot;AdmFee\&quot;: \&quot;${adm_fee}\&quot;,\n    \&quot;CarInsFee\&quot;: \&quot;${carins_fee}\&quot;,\n    \&quot;LifeInsurance\&quot;: \&quot;${lifeins}\&quot;,\n    \&quot;LifeInsuranceFee\&quot;: \&quot;${lifeins_fee}\&quot;,\n    \&quot;ProvisionPercent\&quot;: \&quot;${provisi}\&quot;,\n    \&quot;ProvisionalFee\&quot;: \&quot;${provisi_fee}\&quot;,\n    \&quot;ProvisionalPayment\&quot;: \&quot;${provisi_type}\&quot;,\n    \&quot;FirstPayment\&quot;: \&quot;${firstpay}\&quot;,\n    \&quot;HargaChasis\&quot;: \&quot;\&quot;,\n    \&quot;HargaKaroseri\&quot;: \&quot;\&quot;,\n    \&quot;KolomMutasiDebit\&quot;: \&quot;\&quot;,\n    \&quot;KolomMutasiKredit\&quot;: \&quot;\&quot;,\n    \&quot;KolomMutasiSaldo\&quot;: \&quot;\&quot;,\n    \&quot;Blacklist\&quot;: \&quot;\&quot;,\n    \&quot;plafon\&quot;: \&quot;\&quot;,\n    \&quot;RepeatOrder\&quot;: \&quot;${ro}\&quot;,\n    \&quot;Tujuan\&quot;: \&quot;${tujuan}\&quot;\n  },\n  \&quot;FinancialData\&quot;: {\n    \&quot;cabangKCUBCA\&quot;: \&quot;\&quot;,\n    \&quot;NomorRekening\&quot;: \&quot;\&quot;\n  },\n  \&quot;contactPersonData\&quot;: {\n    \&quot;HubunganDenganDebitor\&quot;: \&quot;\&quot;\n  },\n  \&quot;PenjaminPersonalData\&quot;: {\n    \&quot;NoKTP\&quot;: \&quot;\&quot;,\n    \&quot;Nama\&quot;: \&quot;\&quot;,\n    \&quot;BirthDate\&quot;: \&quot;\&quot;,\n    \&quot;BirthPlace\&quot;: \&quot;\&quot;,\n    \&quot;Jenkel\&quot;: \&quot;\&quot;,\n    \&quot;Alamat\&quot;: \&quot;\&quot;,\n    \&quot;Kelurahan\&quot;: \&quot;\&quot;,\n    \&quot;Kecamatan\&quot;: \&quot;\&quot;,\n    \&quot;kabupaten\&quot;: \&quot;\&quot;,\n    \&quot;Provinsi\&quot;: \&quot;\&quot;,\n    \&quot;Agama\&quot;: \&quot;\&quot;,\n    \&quot;Occupation\&quot;: \&quot;\&quot;\n  },\n  \&quot;PenjaminPasanganData\&quot;: {\n    \&quot;NoKTP\&quot;: \&quot;\&quot;,\n    \&quot;Nama\&quot;: \&quot;\&quot;,\n    \&quot;BirthDate\&quot;: \&quot;\&quot;,\n    \&quot;BirthPlace\&quot;: \&quot;\&quot;,\n    \&quot;Jenkel\&quot;: \&quot;\&quot;,\n    \&quot;Alamat\&quot;: \&quot;\&quot;,\n    \&quot;Kelurahan\&quot;: \&quot;\&quot;,\n    \&quot;Kecamatan\&quot;: \&quot;\&quot;,\n    \&quot;kabupaten\&quot;: \&quot;\&quot;,\n    \&quot;Provinsi\&quot;: \&quot;\&quot;,\n    \&quot;Agama\&quot;: \&quot;\&quot;,\n    \&quot;Occupation\&quot;: \&quot;\&quot;\n  },\n  \&quot;Insurance\&quot;: {\n    \&quot;CarInsuranceCorp\&quot;: \&quot;${carins_corp}\&quot;,\n    \&quot;BranchCarInsurance\&quot;: \&quot;${carins_branch}\&quot;,\n    \&quot;InsuranceType\&quot;: \&quot;${ins_type}\&quot;,\n    \&quot;RSCC\&quot;: \&quot;${rscc}\&quot;,\n    \&quot;RSMB\&quot;: \&quot;${rsmb}\&quot;,\n    \&quot;TJH\&quot;: \&quot;\&quot;,\n    \&quot;InsuranceDeduction\&quot;: \&quot;\&quot;,\n    \&quot;InsurancePayment\&quot;: \&quot;\&quot;,\n    \&quot;LifeInsuranceCorp\&quot;: \&quot;${lifeins_corp}\&quot;,\n    \&quot;BranchLifeInsurance\&quot;: \&quot;${lifeins_branch}\&quot;\n  },\n  \&quot;OtherData\&quot;: {\n    \&quot;Bukti\&quot;: \&quot;\&quot;,\n    \&quot;LuasTanah\&quot;: \&quot;\&quot;,\n    \&quot;LuasBangunan\&quot;: \&quot;\&quot;\n  },\n  \&quot;General\&quot;: {\n    \&quot;JenisCluster\&quot;: \&quot;\&quot;,\n    \&quot;SalesType\&quot;: \&quot;\&quot;,\n    \&quot;SalesAgent\&quot;: \&quot;\&quot;,\n    \&quot;SalesOffice\&quot;: \&quot;\&quot;,\n    \&quot;Packet\&quot;: \&quot;${packet}\&quot;\n  },\n  \&quot;BPKB\&quot;: {\n    \&quot;BodyNumber\&quot;: \&quot;${bodyno}\&quot;,\n    \&quot;BPKBOwner\&quot;: \&quot;${bpkbowner}\&quot;,\n    \&quot;Color\&quot;: \&quot;${color}\&quot;,\n    \&quot;Engineno\&quot;: \&quot;${engineno}\&quot;\n  },\n  \&quot;KartuKeluarga\&quot;: {\n    \&quot;Pendidikan\&quot;: \&quot;\&quot;\n  },\n  \&quot;NPWP\&quot;: {\n    \&quot;Nomor\&quot;: \&quot;\&quot;\n  },\n  \&quot;CoverBukuTabungan\&quot;: {\n    \&quot;Cabang\&quot;: \&quot;\&quot;\n  },\n  \&quot;KartuNamaPasangan\&quot;: {\n    \&quot;KodeFax\&quot;: \&quot;\&quot;\n  },\n  \&quot;FAP\&quot;: {\n    \&quot;HomeAddress\&quot;: \&quot;\&quot;,\n    \&quot;HomeStatus\&quot;: \&quot;\&quot;,\n    \&quot;Kelurahan\&quot;: \&quot;\&quot;,\n    \&quot;Kecamatan\&quot;: \&quot;\&quot;,\n    \&quot;Kabupaten\&quot;: \&quot;\&quot;,\n    \&quot;Provinsi\&quot;: \&quot;\&quot;,\n    \&quot;KodePos\&quot;: \&quot;\&quot;,\n    \&quot;LamaTinggalTahun\&quot;: \&quot;\&quot;,\n    \&quot;LamaTinggalBulan\&quot;: \&quot;\&quot;,\n    \&quot;SupportPerson\&quot;: \&quot;\&quot;,\n    \&quot;MailAddress\&quot;: \&quot;\&quot;,\n    \&quot;OtherMailAddress\&quot;: \&quot;\&quot;,\n    \&quot;KodyaOther\&quot;: \&quot;\&quot;,\n    \&quot;Provinsiother\&quot;: \&quot;\&quot;,\n    \&quot;PostalCodeother\&quot;: \&quot;\&quot;,\n    \&quot;EmailOffice\&quot;: \&quot;\&quot;,\n    \&quot;KodeTelpOffice1\&quot;: \&quot;\&quot;,\n    \&quot;NomortelpOffice1\&quot;: \&quot;\&quot;,\n    \&quot;KodeTelpOffice2\&quot;: \&quot;\&quot;,\n    \&quot;NomorTelpOffice2\&quot;: \&quot;\&quot;,\n    \&quot;KodeTelpOffice3\&quot;: \&quot;\&quot;,\n    \&quot;NomorTelepon3\&quot;: \&quot;\&quot;,\n    \&quot;PrefixHandphone1\&quot;: \&quot;\&quot;,\n    \&quot;NomorHandphone1\&quot;: \&quot;\&quot;,\n    \&quot;PrefixHandphone2\&quot;: \&quot;\&quot;,\n    \&quot;NomorHandphone2\&quot;: \&quot;\&quot;,\n    \&quot;NamaContactPerson\&quot;: \&quot;\&quot;,\n    \&quot;AlamatContactPerson\&quot;: \&quot;\&quot;,\n    \&quot;KotaContactPerson\&quot;: \&quot;\&quot;,\n    \&quot;KodePosContactPerson\&quot;: \&quot;\&quot;,\n    \&quot;kodeTelpContactperson\&quot;: \&quot;\&quot;,\n    \&quot;NomorTeleponContactPerson\&quot;: \&quot;\&quot;,\n    \&quot;RelationshipwithDebitor\&quot;: \&quot;\&quot;,\n    \&quot;PaymentMethod\&quot;: \&quot;\&quot;\n  }\n}\n&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic YmNhZmFwcHM6QWRtaXVuMTIz</value>
   </httpHeaderProperties>
   <katalonVersion>8.1.0</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>http://192.168.29.193:9977/api/EngineScoreMobile/SearchME</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>'9999'</defaultValue>
      <description></description>
      <id>045cd2df-7a22-4691-91a2-f1ee1fe71c49</id>
      <masked>false</masked>
      <name>MID</name>
   </variables>
   <variables>
      <defaultValue>'Aprova &amp; Mobile Entry'</defaultValue>
      <description></description>
      <id>3a1727b2-6f4e-47b4-bec6-6a2b064b1f71</id>
      <masked>false</masked>
      <name>source</name>
   </variables>
   <variables>
      <defaultValue>'192.168.29.1'</defaultValue>
      <description></description>
      <id>cbf73b1b-2e8a-4605-bafe-eb25d0129772</id>
      <masked>false</masked>
      <name>ip</name>
   </variables>
   <variables>
      <defaultValue>'emobile'</defaultValue>
      <description></description>
      <id>62191ebb-2e28-42fd-89a1-ddd016d149bd</id>
      <masked>false</masked>
      <name>userid</name>
   </variables>
   <variables>
      <defaultValue>'KKB'</defaultValue>
      <description></description>
      <id>b8699753-c5fd-416d-819f-d742635be9d0</id>
      <masked>false</masked>
      <name>branch</name>
   </variables>
   <variables>
      <defaultValue>'Perorangan'</defaultValue>
      <description></description>
      <id>b44cb1d1-0c0e-46d6-8819-bcf9deb0055e</id>
      <masked>false</masked>
      <name>tipekons</name>
   </variables>
   <variables>
      <defaultValue>'Married'</defaultValue>
      <description></description>
      <id>bfe6d218-3ded-4dad-ac76-488d93b6bba2</id>
      <masked>false</masked>
      <name>marital</name>
   </variables>
   <variables>
      <defaultValue>'Tidak Ada'</defaultValue>
      <description></description>
      <id>86590425-b1d7-43fd-9ecc-883aa2baacc9</id>
      <masked>false</masked>
      <name>penjamin</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0cdcb4fe-e663-491a-b399-068f0f9088d1</id>
      <masked>false</masked>
      <name>tipepenjamin</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9d5e3b03-2209-472b-ab66-8aebd385ed61</id>
      <masked>false</masked>
      <name>cluster</name>
   </variables>
   <variables>
      <defaultValue>'Ahmad'</defaultValue>
      <description></description>
      <id>ed68b867-7bdd-4b9a-bb99-4e7f6866191f</id>
      <masked>false</masked>
      <name>custname</name>
   </variables>
   <variables>
      <defaultValue>'KTP'</defaultValue>
      <description></description>
      <id>d7265e0f-3bff-433c-9ef5-fcdd15b894c3</id>
      <masked>false</masked>
      <name>id_type</name>
   </variables>
   <variables>
      <defaultValue>'320104100695007'</defaultValue>
      <description></description>
      <id>81f18a0f-63b8-406a-9e82-3ba73086b47c</id>
      <masked>false</masked>
      <name>id_no</name>
   </variables>
   <variables>
      <defaultValue>'Bogor'</defaultValue>
      <description></description>
      <id>1a457b90-cd27-48c3-8efa-fb1fa1444878</id>
      <masked>false</masked>
      <name>birthplace</name>
   </variables>
   <variables>
      <defaultValue>'10-06-1995'</defaultValue>
      <description></description>
      <id>4f837fe8-091d-4326-b157-3d9b1d27e9d8</id>
      <masked>false</masked>
      <name>birthdate</name>
   </variables>
   <variables>
      <defaultValue>'CILEBUT POS'</defaultValue>
      <description></description>
      <id>d03af04c-1026-459f-8875-8cc9c00b2e05</id>
      <masked>false</masked>
      <name>alamatktp</name>
   </variables>
   <variables>
      <defaultValue>'CILEBUT TIMUR'</defaultValue>
      <description></description>
      <id>7928a163-b9ad-41d8-a23e-580b218e2e79</id>
      <masked>false</masked>
      <name>kelurahan</name>
   </variables>
   <variables>
      <defaultValue>'SUKARAJA'</defaultValue>
      <description></description>
      <id>8d8f743e-c958-477a-8278-03734f2de688</id>
      <masked>false</masked>
      <name>kecamatan</name>
   </variables>
   <variables>
      <defaultValue>'KABUPATEN'</defaultValue>
      <description></description>
      <id>be0d2765-30cc-4487-a370-eb890eef8591</id>
      <masked>false</masked>
      <name>kabupaten</name>
   </variables>
   <variables>
      <defaultValue>'PROVINSI JAWA BARAT'</defaultValue>
      <description></description>
      <id>c0c711ba-49e3-4ea0-a98f-d39a10521b0e</id>
      <masked>false</masked>
      <name>provinsi</name>
   </variables>
   <variables>
      <defaultValue>'10130'</defaultValue>
      <description></description>
      <id>46ec0aeb-7776-4b49-8b13-4935e7e12615</id>
      <masked>false</masked>
      <name>kodepos</name>
   </variables>
   <variables>
      <defaultValue>'Laki-laki'</defaultValue>
      <description></description>
      <id>d5754072-dd74-4adf-adce-8fe446f6c3db</id>
      <masked>false</masked>
      <name>jenkel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>78c875c0-11d4-4272-961a-536cb4202281</id>
      <masked>false</masked>
      <name>supperson</name>
   </variables>
   <variables>
      <defaultValue>'Leni'</defaultValue>
      <description></description>
      <id>20973e03-bce9-4e19-ad8f-1bffe4d515de</id>
      <masked>false</masked>
      <name>namaibu</name>
   </variables>
   <variables>
      <defaultValue>'Islam'</defaultValue>
      <description></description>
      <id>d134e1ef-9e53-49cb-bd91-6ba4c8a75543</id>
      <masked>false</masked>
      <name>agama</name>
   </variables>
   <variables>
      <defaultValue>'Wiraswasta'</defaultValue>
      <description></description>
      <id>3c88f37b-7118-4ea7-9035-51a6f980f771</id>
      <masked>false</masked>
      <name>job</name>
   </variables>
   <variables>
      <defaultValue>'111202'</defaultValue>
      <description></description>
      <id>05b7785d-2505-434f-b5db-271f888a027c</id>
      <masked>false</masked>
      <name>ecocode</name>
   </variables>
   <variables>
      <defaultValue>'2008'</defaultValue>
      <description></description>
      <id>53e67dba-e94d-4227-adb5-79e2040c625f</id>
      <masked>false</masked>
      <name>est_since</name>
   </variables>
   <variables>
      <defaultValue>'Makanan'</defaultValue>
      <description></description>
      <id>be14d496-fa09-410d-ad5a-c3cd3eb3d9b5</id>
      <masked>false</masked>
      <name>jenisusaha</name>
   </variables>
   <variables>
      <defaultValue>'Pemilik'</defaultValue>
      <description></description>
      <id>fb4d3ada-fa7d-4f41-a930-db174f6ac5bd</id>
      <masked>false</masked>
      <name>jabatan</name>
   </variables>
   <variables>
      <defaultValue>'25,000,000'</defaultValue>
      <description></description>
      <id>93bbd1ca-f8a9-4435-93a9-09b272c25967</id>
      <masked>false</masked>
      <name>income</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>58b9b9b2-1341-4066-8b36-7ade3bc636e2</id>
      <masked>false</masked>
      <name>alamat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ad61ed14-4fdc-49b6-b93b-b023d7ae2ff9</id>
      <masked>false</masked>
      <name>fax</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6787f1aa-1f99-4874-b66b-f77b58b097d5</id>
      <masked>false</masked>
      <name>kodepos1</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>41bef6cc-fd6d-4829-a583-34312087cc11</id>
      <masked>false</masked>
      <name>kodetlp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fc9ccf9e-6079-4dd8-ab71-7d27ec733c6a</id>
      <masked>false</masked>
      <name>tlpno</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>33a1242d-139e-483c-af94-09a0b4f9870c</id>
      <masked>false</masked>
      <name>ext</name>
   </variables>
   <variables>
      <defaultValue>'SEPTI INDRI'</defaultValue>
      <description></description>
      <id>f62cd838-012d-483e-aa0a-15318ec143c3</id>
      <masked>false</masked>
      <name>spouse_name</name>
   </variables>
   <variables>
      <defaultValue>'KTP'</defaultValue>
      <description></description>
      <id>406187e3-473d-4699-bc05-db04e15842a9</id>
      <masked>false</masked>
      <name>spouse_idtype</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>66dee500-de10-4f85-9f12-7ac53bf4e65e</id>
      <masked>false</masked>
      <name>spouse_jenkel</name>
   </variables>
   <variables>
      <defaultValue>'3111075106820021'</defaultValue>
      <description></description>
      <id>181d37a4-83c3-47a7-b1d4-fc2a6fa8d33b</id>
      <masked>false</masked>
      <name>spouse_idno</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6703b6a6-455a-4c5f-82bd-f69280fa068d</id>
      <masked>false</masked>
      <name>spouse_agama</name>
   </variables>
   <variables>
      <defaultValue>'11-11-1993'</defaultValue>
      <description></description>
      <id>feb4b38c-5d70-4536-95e2-c3990847aec3</id>
      <masked>false</masked>
      <name>spouse_birthdate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cb974c8f-dc2b-4ee1-80c8-7560253eb99d</id>
      <masked>false</masked>
      <name>spouse_birthplace</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b35d1433-23c0-409b-9f03-9f65ded80e8f</id>
      <masked>false</masked>
      <name>spouse_alamat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c9719446-6a48-47f6-99f3-7c2e09d17993</id>
      <masked>false</masked>
      <name>spouse_kel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1836f415-2124-48a2-8704-4946fbae09cd</id>
      <masked>false</masked>
      <name>spouse_kec</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b6318091-9063-445a-a3e0-1d469787e7c9</id>
      <masked>false</masked>
      <name>spouse_kab</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f5a05ef1-2458-4ec6-83f8-7dc3f6a0edfc</id>
      <masked>false</masked>
      <name>spouse_prov</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>87cbd7ae-dda3-4158-9953-622597f8e689</id>
      <masked>false</masked>
      <name>spouse_occ_ktp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bdca0940-e9a9-4496-840d-09031488d170</id>
      <masked>false</masked>
      <name>spouse_nama_occ</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3cf3ea10-2f44-4951-be95-d46f2313a93b</id>
      <masked>false</masked>
      <name>spouse_jabatan</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2826b145-882b-4b66-91a0-7fdea7508a95</id>
      <masked>false</masked>
      <name>spouse_occ_kartunama</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>710e7749-d3d3-4e0a-a833-2785628da638</id>
      <masked>false</masked>
      <name>spouse_alamat_occ</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>567751c1-a11d-43a2-b0ff-d9baf7d70156</id>
      <masked>false</masked>
      <name>spouse_fax</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>89bac96e-43fc-4ab4-8471-948fbc159576</id>
      <masked>false</masked>
      <name>spouse_kec_occ</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d9db6422-9ee1-47a5-a6ab-88f5eded7a05</id>
      <masked>false</masked>
      <name>spouse_kodepos_occ</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4a70ca50-d68a-435d-bbad-3d6ed3e34b9d</id>
      <masked>false</masked>
      <name>spouse_kodetlp_occ</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9eb7c5e3-a6b3-4fbc-bf8f-aa2f2f871ca1</id>
      <masked>false</masked>
      <name>spouse_notlp_occ</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>24914635-b3bb-4f64-a0f2-89384484c560</id>
      <masked>false</masked>
      <name>spouse_ext_occ</name>
   </variables>
   <variables>
      <defaultValue>'Wahana Persada Jakarta'</defaultValue>
      <description></description>
      <id>f5667d2a-302f-4914-b19d-de5b58dd26c3</id>
      <masked>false</masked>
      <name>dealername</name>
   </variables>
   <variables>
      <defaultValue>'W073-Wahana Persada Jakarta'</defaultValue>
      <description></description>
      <id>fe838e44-de32-4c5a-8042-0a25ed16f7ca</id>
      <masked>false</masked>
      <name>dealerbranch</name>
   </variables>
   <variables>
      <defaultValue>'Jln. Alternatif Cibubur Rt. 001 Rw 007, Kampung Nagewer'</defaultValue>
      <description></description>
      <id>860e8374-159d-47aa-a53c-6ae8c51835c9</id>
      <masked>false</masked>
      <name>dealer_addr</name>
   </variables>
   <variables>
      <defaultValue>'Bogor'</defaultValue>
      <description></description>
      <id>35481420-91df-4b58-94ab-057f77515a4e</id>
      <masked>false</masked>
      <name>dealer_kota</name>
   </variables>
   <variables>
      <defaultValue>'0218234370'</defaultValue>
      <description></description>
      <id>37745d17-c7a6-45ee-ac39-5da0ed262dbd</id>
      <masked>false</masked>
      <name>dealer_hp</name>
   </variables>
   <variables>
      <defaultValue>'02182494927'</defaultValue>
      <description></description>
      <id>0b3ffa97-5eb1-4f83-833e-cd15a53c0657</id>
      <masked>false</masked>
      <name>dealer_fax</name>
   </variables>
   <variables>
      <defaultValue>'1'</defaultValue>
      <description></description>
      <id>0e709c16-0db3-44ee-bb95-a9693ed3a9d0</id>
      <masked>false</masked>
      <name>dealer_auth</name>
   </variables>
   <variables>
      <defaultValue>'7160051510'</defaultValue>
      <description></description>
      <id>326758aa-0fc5-46e1-a2d8-1c97139e5da1</id>
      <masked>false</masked>
      <name>dealer_norek</name>
   </variables>
   <variables>
      <defaultValue>'NEW'</defaultValue>
      <description></description>
      <id>496c27ee-776a-4880-a5c3-33a6078fc72d</id>
      <masked>false</masked>
      <name>car_cond</name>
   </variables>
   <variables>
      <defaultValue>'DATSUN'</defaultValue>
      <description></description>
      <id>58d5318c-8f8f-4ee3-91a9-87b89843b89d</id>
      <masked>false</masked>
      <name>brand</name>
   </variables>
   <variables>
      <defaultValue>'GO PANCA'</defaultValue>
      <description></description>
      <id>dd5c93e9-2125-42f2-8bd2-107e6cd98e84</id>
      <masked>false</masked>
      <name>model</name>
   </variables>
   <variables>
      <defaultValue>'GO PANCA T 1.2 M/T'</defaultValue>
      <description></description>
      <id>7b64c526-703f-4cd6-aa6a-24867aeed7f6</id>
      <masked>false</masked>
      <name>type</name>
   </variables>
   <variables>
      <defaultValue>'2020'</defaultValue>
      <description></description>
      <id>e2c1b967-7d5e-4d05-91eb-31026d69df07</id>
      <masked>false</masked>
      <name>year</name>
   </variables>
   <variables>
      <defaultValue>'Mb. Penumpang'</defaultValue>
      <description></description>
      <id>2be30955-3c5a-488c-90d0-d5a89c4bd9b2</id>
      <masked>false</masked>
      <name>kind</name>
   </variables>
   <variables>
      <defaultValue>'Personal'</defaultValue>
      <description></description>
      <id>652daf84-cb6f-4ccd-bed6-5677ef5163c1</id>
      <masked>false</masked>
      <name>purpose</name>
   </variables>
   <variables>
      <defaultValue>'Hitam'</defaultValue>
      <description></description>
      <id>0186b9e8-bb90-4152-9c78-70e18af997fa</id>
      <masked>false</masked>
      <name>color</name>
   </variables>
   <variables>
      <defaultValue>'e53737'</defaultValue>
      <description></description>
      <id>145bb0f8-02b7-4892-b92b-c3d28f08f1ca</id>
      <masked>false</masked>
      <name>engineno</name>
   </variables>
   <variables>
      <defaultValue>'b63737'</defaultValue>
      <description></description>
      <id>c4135b39-e27b-4b95-90f7-f18aa704613c</id>
      <masked>false</masked>
      <name>bodyno</name>
   </variables>
   <variables>
      <defaultValue>'AHMAD'</defaultValue>
      <description></description>
      <id>1d529ddf-51f9-4fda-8314-aa9cf3ed2df0</id>
      <masked>false</masked>
      <name>bpkb_owner</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cc062e0b-a593-4955-8943-52ee16a53298</id>
      <masked>false</masked>
      <name>policeno</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6361f1e7-83d9-4ecd-8b54-d8bf22d8bbbe</id>
      <masked>false</masked>
      <name>bpkbno</name>
   </variables>
   <variables>
      <defaultValue>'250000000'</defaultValue>
      <description></description>
      <id>fe341d88-2a0e-43cd-9834-35023089a9fb</id>
      <masked>false</masked>
      <name>otr</name>
   </variables>
   <variables>
      <defaultValue>'75000000'</defaultValue>
      <description></description>
      <id>cc0d234c-4b80-421e-bdb9-fa432e3a9950</id>
      <masked>false</masked>
      <name>dp</name>
   </variables>
   <variables>
      <defaultValue>'30'</defaultValue>
      <description></description>
      <id>30d145e9-12ef-4ba4-9ea4-5ddfe78eb3b0</id>
      <masked>false</masked>
      <name>dp_percent</name>
   </variables>
   <variables>
      <defaultValue>'175000000'</defaultValue>
      <description></description>
      <id>39ffdb96-64b3-4c74-8dbd-8b80ef622072</id>
      <masked>false</masked>
      <name>principal</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6b1e7d00-4d46-4d14-9cad-7da792b64d51</id>
      <masked>false</masked>
      <name>res_value</name>
   </variables>
   <variables>
      <defaultValue>'36'</defaultValue>
      <description></description>
      <id>0033ee6d-7f8e-4dde-a0c1-e8826c9c21da</id>
      <masked>false</masked>
      <name>tenor</name>
   </variables>
   <variables>
      <defaultValue>'2.999999'</defaultValue>
      <description></description>
      <id>10a3817e-0937-464f-b61b-43ea673a3075</id>
      <masked>false</masked>
      <name>flatrate</name>
   </variables>
   <variables>
      <defaultValue>'6.016893'</defaultValue>
      <description></description>
      <id>c6e35dd7-8770-42f3-8c97-b1bfe16c3608</id>
      <masked>false</masked>
      <name>effrate</name>
   </variables>
   <variables>
      <defaultValue>'5298611'</defaultValue>
      <description></description>
      <id>10690c96-4b3f-42d5-a3a3-2b98911da737</id>
      <masked>false</masked>
      <name>installment</name>
   </variables>
   <variables>
      <defaultValue>'In Advance'</defaultValue>
      <description></description>
      <id>1f6827bc-a37a-4d5c-9860-718b5b15f857</id>
      <masked>false</masked>
      <name>loan_type</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d299897e-efe1-45a0-a816-028a510d4638</id>
      <masked>false</masked>
      <name>outstanding</name>
   </variables>
   <variables>
      <defaultValue>'13839000'</defaultValue>
      <description></description>
      <id>2b487d35-ff5e-47a8-9b3d-1f39f1b18533</id>
      <masked>false</masked>
      <name>biaya_pp</name>
   </variables>
   <variables>
      <defaultValue>'1000000'</defaultValue>
      <description></description>
      <id>2f8c6a9a-5299-453d-b6be-e86622b8e284</id>
      <masked>false</masked>
      <name>adm_fee</name>
   </variables>
   <variables>
      <defaultValue>'14000'</defaultValue>
      <description></description>
      <id>71d7644e-ca8a-4474-85be-0caf467d90f2</id>
      <masked>false</masked>
      <name>carins_fee</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>1fc6d165-7cab-4c12-8e9d-209de7ea734c</id>
      <masked>false</masked>
      <name>lifeins_fee</name>
   </variables>
   <variables>
      <defaultValue>'0'</defaultValue>
      <description></description>
      <id>23a3890f-05f1-4813-9e59-982ebe4867ec</id>
      <masked>false</masked>
      <name>lifeins</name>
   </variables>
   <variables>
      <defaultValue>'1.00'</defaultValue>
      <description></description>
      <id>1d05ccb4-a589-4b7d-add3-5b2add8abb09</id>
      <masked>false</masked>
      <name>provisi</name>
   </variables>
   <variables>
      <defaultValue>'1750000'</defaultValue>
      <description></description>
      <id>f16f5f0d-49b3-4694-b1d7-6bb062681c19</id>
      <masked>false</masked>
      <name>provisi_fee</name>
   </variables>
   <variables>
      <defaultValue>'Prepaid'</defaultValue>
      <description></description>
      <id>0aeb8744-4a84-450b-b58a-0d7a3ed63226</id>
      <masked>false</masked>
      <name>provisi_type</name>
   </variables>
   <variables>
      <defaultValue>'95887700'</defaultValue>
      <description></description>
      <id>024eddf9-cb5d-40c5-9c5e-87e7c845c83f</id>
      <masked>false</masked>
      <name>firstpay</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d17c2215-911c-40ca-b0b1-f27a5ba8eabe</id>
      <masked>false</masked>
      <name>hargachasis</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6668b788-27a2-447c-b80a-1498c2a5fc91</id>
      <masked>false</masked>
      <name>hargakaroseri</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c2d3cc57-c6a1-446e-a474-a92a5ab50788</id>
      <masked>false</masked>
      <name>kolommutasidebit</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8c2d454e-475a-4c90-b666-7b12e2b58952</id>
      <masked>false</masked>
      <name>kolommutasisaldo</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>21306bc4-f576-4ab0-8b0e-91ebf4a4c5b7</id>
      <masked>false</masked>
      <name>blacklist</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2e64f4a3-2a6e-4f6f-a033-3ff31c21bb56</id>
      <masked>false</masked>
      <name>plafon</name>
   </variables>
   <variables>
      <defaultValue>'Yes'</defaultValue>
      <description></description>
      <id>8832d0e7-3589-4de3-943c-34053031606c</id>
      <masked>false</masked>
      <name>ro</name>
   </variables>
   <variables>
      <defaultValue>'Personal'</defaultValue>
      <description></description>
      <id>80d8b0a0-ab00-4015-aa30-6e1f4170b48a</id>
      <masked>false</masked>
      <name>tujuan</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e1f2f663-c60e-4c85-82eb-e9e5f58493f4</id>
      <masked>false</masked>
      <name>kcu_branch</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>93365627-013b-4160-a4e7-40d4aad4b66e</id>
      <masked>false</masked>
      <name>norek_bca</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b48bf97c-b594-4001-a680-a20b191faf4d</id>
      <masked>false</masked>
      <name>hub_debitor</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c04a86a0-bfe2-491e-b4de-14d26d09310b</id>
      <masked>false</masked>
      <name>penj_ktpno</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ffe28a93-2c62-4217-b357-e7182a17c179</id>
      <masked>false</masked>
      <name>penj_nama</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>eb5d65d2-a255-43d6-8f0a-eb9a8a56e02d</id>
      <masked>false</masked>
      <name>penj_birthdate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d8dd9eea-bf9a-4837-9224-8f96af1a5e17</id>
      <masked>false</masked>
      <name>penj_birtplace</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cd48d3f0-34af-4f90-ab12-956e5205d9ac</id>
      <masked>false</masked>
      <name>penj_jenkel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bd6ba7f8-e0a8-4e75-871f-026d04c4b23e</id>
      <masked>false</masked>
      <name>penj_alamat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1ae8799b-bb9a-4ad9-8b6c-52282c2dfd7e</id>
      <masked>false</masked>
      <name>penj_kel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2be6cdd7-722b-4745-9949-ec3072b66b78</id>
      <masked>false</masked>
      <name>penj_kec</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d435e2b4-ff8a-4c10-b987-6ae025b703b8</id>
      <masked>false</masked>
      <name>penj_kab</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fdae66b4-b4c8-436f-ad29-07a250d1c2f5</id>
      <masked>false</masked>
      <name>penj_prov</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>09f800ec-4d7f-4e08-8b50-731761179825</id>
      <masked>false</masked>
      <name>penj_agama</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1c28c363-16fc-4082-b7cc-515039fecd55</id>
      <masked>false</masked>
      <name>penj_occ</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6816f4cb-0dc0-4062-a106-824e5cb04606</id>
      <masked>false</masked>
      <name>penj_spouse_ktp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e1c7694e-068d-44e6-b00d-41d6763f3b09</id>
      <masked>false</masked>
      <name>penj_spouse_name</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9f469eb9-eda5-47ef-b154-838a2ddc6b4b</id>
      <masked>false</masked>
      <name>penj_spouse_birthdate</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f49b6aee-e37d-40b3-8946-acaf52b48fc4</id>
      <masked>false</masked>
      <name>penj_spouse_birthplace</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>49a1c953-d175-4634-8aef-198b615da90a</id>
      <masked>false</masked>
      <name>penj_spouse_jenkel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d6d4ed26-7e79-45f8-b27d-83c32d0f6130</id>
      <masked>false</masked>
      <name>penj_spouse_alamat</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>85414442-9fea-43b1-9704-c9781e28b682</id>
      <masked>false</masked>
      <name>penj_spouse_kel</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b4fdf10a-f29c-4cdf-beab-22ed61babb5b</id>
      <masked>false</masked>
      <name>penj_spouse_kec</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d00bf4e3-1a75-448f-a0c4-9b515585a475</id>
      <masked>false</masked>
      <name>penj_spouse_kab</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0e18f44a-96e2-468b-83a5-be61cc467340</id>
      <masked>false</masked>
      <name>penj_spouse_prov</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>dfb588d1-ba0f-446b-a91c-4dd3bbcc7f87</id>
      <masked>false</masked>
      <name>penj_spouse_agama</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2f0e1523-27d0-4d78-8c42-f86436125df3</id>
      <masked>false</masked>
      <name>penj_spouse_occ</name>
   </variables>
   <variables>
      <defaultValue>'NEW - SINAR MAS'</defaultValue>
      <description></description>
      <id>22788034-702c-4e3e-b040-014c2d0f816a</id>
      <masked>false</masked>
      <name>carins_corp</name>
   </variables>
   <variables>
      <defaultValue>'(NSMS012) TIPE 3 - W2 - CS'</defaultValue>
      <description></description>
      <id>8a5ac05c-de6b-4c6b-ae09-cdd09429ced0</id>
      <masked>false</masked>
      <name>carins_branch</name>
   </variables>
   <variables>
      <defaultValue>'TLO,ALL RISK,ALL RISK'</defaultValue>
      <description></description>
      <id>aeadd03a-6839-45fd-ac87-506e193642a7</id>
      <masked>false</masked>
      <name>ins_type</name>
   </variables>
   <variables>
      <defaultValue>'No'</defaultValue>
      <description></description>
      <id>a7444c50-17c8-43ba-9ff6-76db52a8e435</id>
      <masked>false</masked>
      <name>rscc</name>
   </variables>
   <variables>
      <defaultValue>'Yes'</defaultValue>
      <description></description>
      <id>e5893606-466b-4624-8b0e-13d90f0ef8ea</id>
      <masked>false</masked>
      <name>rsmb</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f9075655-669e-404a-aed0-0cff7e45bd9f</id>
      <masked>false</masked>
      <name>tjh</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>06f83d63-b281-41eb-93d8-2878aadf4d41</id>
      <masked>false</masked>
      <name>ins_deduc</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>52b0600f-66d3-4978-ad40-b4408a955a1e</id>
      <masked>false</masked>
      <name>ins_payment</name>
   </variables>
   <variables>
      <defaultValue>'(01299) PT. ASURANSI JIWA BCA'</defaultValue>
      <description></description>
      <id>bcaeed45-23a1-43e1-afa6-9e8053d4ea20</id>
      <masked>false</masked>
      <name>lifeins_corp</name>
   </variables>
   <variables>
      <defaultValue>'(01299-20) FULL COVER (ENTRY>01-09-2018)'</defaultValue>
      <description></description>
      <id>4f13633a-af10-4947-a3ba-71489c48c018</id>
      <masked>false</masked>
      <name>lifeins_branch</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>13e779a4-defa-48e6-b92b-7df619517004</id>
      <masked>false</masked>
      <name>other_bukti</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cc19c4d3-ec71-4d39-bbd4-2f6f3c16e9b5</id>
      <masked>false</masked>
      <name>other_luastanah</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2301631a-2c00-4033-a0fe-e276fa4f7f9e</id>
      <masked>false</masked>
      <name>other_luasbangunan</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>15533625-8527-4f6f-8f83-3e3522a5d5d1</id>
      <masked>false</masked>
      <name>jenis_cluster</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d76ba2bf-7d96-4715-b1aa-dc5b9f293659</id>
      <masked>false</masked>
      <name>salestype</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ee084b66-597c-4308-9e14-074e9a85af17</id>
      <masked>false</masked>
      <name>salesagent</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d1909aaf-cad9-420f-b4e7-f4a1d7c2e645</id>
      <masked>false</masked>
      <name>salesoffice</name>
   </variables>
   <variables>
      <defaultValue>'(000) Non Packet'</defaultValue>
      <description></description>
      <id>f04288ce-de74-41fa-8ab2-dbce88ece4f6</id>
      <masked>false</masked>
      <name>packet</name>
   </variables>
   <variables>
      <defaultValue>'AHMAD'</defaultValue>
      <description></description>
      <id>e7f52dbc-6f5b-4c07-9f4f-a9828c89e7aa</id>
      <masked>false</masked>
      <name>bpkbowner</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>14f42924-5c3a-48ed-ac32-218f2e8e71db</id>
      <masked>false</masked>
      <name>pendidikan</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0ee4d409-b363-455b-a6f8-9f77fd4fff0b</id>
      <masked>false</masked>
      <name>npwp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>5ad36e13-ea3c-4fbe-b7ab-ce12af31505e</id>
      <masked>false</masked>
      <name>bukutab_cabang</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
